name: amplify_flutter

packages:
  - packages/**

scripts:
  build:examples:prepare: >
    melos exec --scope="*example*" --fail-fast -- \
      cp ../../../.circleci/dummy_amplifyconfiguration.dart lib/amplifyconfiguration.dart

  # Build iOS plugin example apps.
  build:examples:ios: >
    melos exec -c 1 --scope="*example*" --fail-fast -- \
      flutter build ios --no-codesign

  # Build Android plugin example apps.
  build:examples:android: >
    melos exec --scope="*example*" --fail-fast -- \
      flutter build apk --debug

  # Run flutter tests.
  test:unit:flutter: >
    ./.circleci/test_all_plugins.sh flutter-test && exit 0

  # Run android unit tests
  test:unit:android: >
    ./.circleci/test_all_plugins.sh android-test && exit 0

  analyze: melos exec -- pub global run tuneup check
  postbootstrap: tuneup --version || pub global activate tuneup
  postclean: melos exec -- rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea

dev_dependencies:
  pedantic: ^1.8.0
